version: '3.3'

services:
  duui-backend:
    build:
      context: ./DUUIRestService
      dockerfile: Dockerfile      # or Dockerfile-rest-service, if that's the file name
    container_name: duui-gateway-backend
    volumes:
      # Mount the Docker socket so the backend can start containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./DUUIRestService/files:/app/drives:cached
    environment:
      - PORT=2605
      - HOST=duui-gateway-backend
      - LOCAL_DRIVE_ROOT=/app/drives
      - MONGO_USER=db_user
      - MONGO_PASSWORD=db_password
      - MONGO_HOST=duui-gateway-database
      - MONGO_DB=duui
      - MONGO_PORT=27017
      - DBX_APP_KEY=
      - DBX_APP_SECRET=
      - DBX_REDIRECT_URL=http://duui-gateway-frontend:5173/account/dropbox
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_REDIRECT_URI=http://duui-gateway-frontend:5173/account/google
      - SMTP_HOST=duui-gateway-smtp
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - MAIL_FROM_EMAIL=help@duui.de
    ports:
      - "8085:2605"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
      - smptp-server
    networks:
      - app-network


  duui-frontend:
    build:
      context: ./DUUIWeb
      dockerfile: Dockerfile      # or Dockerfile-frontend, etc.
      args:
        API_URL: http://duui-gateway-backend:2605
        DBX_URL: https://www.dropbox.com/home/Apps/DUUI
        PUBLIC_VERIFICATION_REQUIRED: 'true'
    container_name: duui-gateway-frontend
    ports:
      - "5173:5173"
    depends_on:
      - duui-backend
    environment:
      - ORIGIN=http://duui-gateway-frontend:5173
      - API_URL=http://duui-gateway-backend:2605
      - PORT=5173
      - DBX_URL='https://www.dropbox.com/home/Apps/DUUI'
      - PUBLIC_VERIFICATION_REQUIRED=true
    networks:
      - app-network

  smptp-server:
    image: mailhog/mailhog
    container_name: duui-gateway-smtp
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network
  mongodb:
    image: mongo:4.4.29
    restart: always
    container_name: duui-gateway-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: duui
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

networks:
    app-network:
        driver: bridge