version: '3.3'

services:
  duui-backend:
    build:
      context: ./DUUIRestService
      dockerfile: Dockerfile      # or Dockerfile-rest-service, if that's the file name
    container_name: duui-gateway-backend
    volumes:
      # Mount the Docker socket so the backend can start containers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MONGO_USER=db_user
      - MONGO_HOST=duui-gateway-database
      - MONGO_DB=duui
      - MONGO_PORT=27017
      - MONGO_PASSWORD=db_password
    ports:
      - "8085:2605"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb


  duui-frontend:
    build:
      context: ./DUUIWeb
      dockerfile: Dockerfile      # or Dockerfile-frontend, etc.
    container_name: duui-gateway-frontend
    ports:
      - "8092:5173"
    depends_on:
      - duui-backend
    environment:
      - ORIGIN=http://duui-gateway-frontend:5173
      - API_URL=http://duui-gateway-backend:2605
      - PORT=5173
      - DBX_URL='https://www.dropbox.com/home/Apps/DUUI'


  mongodb:
    image: mongo:4.4.29
    restart: always
    container_name: duui-gateway-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: duui
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro