name: Build Documentation using MkDocs 
# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch 
# https://medium.com/dev-genius/continuous-deployment-for-mkdocs-with-github-actions-7dceec87f0ea
on: 
  push: 
    branches: [master,main] 
  pull_request: 
    branches: [master,main] 
jobs: 
  build: 
    name: Build and Deploy Documentation 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Master 
        uses: actions/checkout@v2 
      - name: Set up Python
        uses: actions/setup-python@v5 
        with: 
          python-version: '3.x' 
      - name: Install dependencies 
        run: | 
          python -m pip install --upgrade pip 
          pip install mkdocs-material 
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-glightbox
      - name: Deploy 
        run: | 
          mkdocs gh-deploy --config-file Documentation/mkdocs.yml --remote-branch gh-pages --force
